travis:
  secure:
    BINSTAR_TOKEN: T6+8wvvjQrjryZkHH/nLFHYPhFXTv/Hzpjmax+udMEC6gl1bf9Q/svkJCmS21ig1eGvC8blnLpc7NrgDbi4V7s1GUEq94ZQqThA0HOCvTl1Pmm/Ui/9NgV2Tq0fJa5Lib/90x0hvsMjlhKW9RqA50e+BeKIYTN9MA8sRum13NtXgvSvJnT9+zgBTiOcQnENGazV+4bt6+UYjMLlF74EesiSsiKx/NRe1hB07esSNU3KaEcYtY53VQIJvAl8r2kAfH8T5z9EvKRRNfiNOjggDUYM1+awjGCZzl8zsF7YsQRXDGR5sZ+ezKojZccKuCqtQm9XMlr5zZX1gVHhRWtkIQP1HyW5+DntSmFRaj4gT95hyYdbi/LFebdvKslfKhcEAAJTx6PkSy0WT4WxbJFOPMbdRzwkUS/pDcjY1U16JEm9JBuIKgwD9ZuzfsgV9PAYIF9aDQtWrP9E1jkYEECB7Uxds+1S8XmSK+J42vPGr1Z9rAgsY88Mu2dxsNLjKTR/ctskc+wVAhQTNyg3IdPy/YWg0Y6fIqjRwECxlf9Evmx3m4h16RUHBK8WG3QZq1RxQPQMlYq466RKlQzuBM7A2w8uGduS48FFRTGM6SB6yQngUUFUZr43Ec6wwCyiG+kXbKvhP26rLNT7UW32iQ7rrR5CG9ufKukF8RabKAAE4i90=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
