travis:
  secure:
    BINSTAR_TOKEN: Y004FhaZ5E0RcZgoZYFinK2fqIPJyueMqFmz6q61xqG09EGE3a6w3QAzqYWlJZ1dDBVRKHt2CuDQW46y9cxk+nbPrHSB9FE10hRqYqHdGeWERG5KlC4udsYHPUiLM0p9pFDE/IwYmv1Tu8vR7TaKVKz4sFKmZbjOv20diEBZH599kKiOZfuRqnm2iPdBrps5o9X8byxrsv74zGz843AlZw3oMmLlreGd4/EK2JBnTvIIH0X8q2ydjXghVPduhL185WEND/q4yAY68G5UZgQZiiaeoaE3Crd5Ouux7ykqTDWYHx9RptSCtb4MjZ6HUCK/WNOLbMG6RZQgLs2HSj2OnkSFhQhNRzDeb8bdDPRRj4ZhrEA5mFqyQreGt8O4BEMbv0j0oxbAHdAqLQLuru5PYT/llupv4KCPKRT+eXH4kaa87g/sGx12mZA2HF0qvWOXE5XKdU74qc1FbFDJDbHHegyeQ/m8tN7d4Kf208hXne9VPnCHBojZxTSqGu7TJVtp9VfrEVeJxJRt4Ub98ghWtpO8ZpRUvC63S1LbE/I1ZkTBBeJHx7C3uSFN1wUfBtWpPbnKWCX+DZC32wo5NDwKGlV5Dk68qVjsssjrPILE8IU2TPVca7KVS4uRd2l9hxtF5PtGFEZReUctLp1Fyovb3Y2Yu0YvSk2iXTMuqd8+ZQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
